/* Generated by scripts/build_style_defaults.py -- do not edit by hand. */

export const style = {
  "bjcp_sensory": {
    "biscuit": [
      "Low to moderate maltiness supports the hop presentation, and may optionally show small amounts of specialty malt character (bready, toasty, biscuit, caramelly)."
    ],
    "bready": [
      "Low to moderate maltiness supports the hop presentation, and may optionally show small amounts of specialty malt character (bready, toasty, biscuit, caramelly)."
    ],
    "caramel": [
      "Low to moderate maltiness supports the hop presentation, and may optionally show small amounts of specialty malt character (bready, toasty, biscuit, caramelly).",
      "Caramel flavors are often absent or fairly restrained (but are acceptable as long as they don\u2019t clash with the hops)."
    ],
    "grainy": [
      "Low to moderate clean grainy-malt character supports the hop presentation, and may optionally show small amounts of specialty malt character (bready, toasty, biscuity)."
    ],
    "toast": [
      "Low to moderate maltiness supports the hop presentation, and may optionally show small amounts of specialty malt character (bready, toasty, biscuit, caramelly)."
    ]
  },
  "category_usage": [
    {
      "max_percent": 100,
      "min_percent": 54,
      "name": "base",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 25,
      "min_percent": 0,
      "name": "munich",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 15,
      "min_percent": 0,
      "name": "crystal",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 1,
      "min_percent": 0,
      "name": "roasted",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 17,
      "min_percent": 0,
      "name": "specialty",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 7,
      "min_percent": 0,
      "name": "flakes and adjuncts",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 4,
      "min_percent": 0,
      "name": "sugar",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 8,
      "min_percent": 0,
      "name": "rye",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 18,
      "min_percent": 0,
      "name": "wheat",
      "unique_fermentable_count": 1
    },
    {
      "max_percent": 0,
      "min_percent": 0,
      "name": "smoked",
      "unique_fermentable_count": 0
    }
  ],
  "default": {
    "abv": 5.4,
    "flavors": [
      {
        "level": 2,
        "name": "grainy"
      },
      {
        "level": 2,
        "name": "biscuit"
      },
      {
        "level": 2,
        "name": "toast"
      },
      {
        "level": 1,
        "name": "bready"
      },
      {
        "level": 1,
        "name": "caramel"
      }
    ],
    "srm": 8
  },
  "grain_usage": [
    {
      "category": "specialty",
      "max_percent": 12,
      "min_percent": 0,
      "name": "Melanoidin Malt",
      "slug": "weyermann-melanoidin-malt"
    },
    {
      "category": "sugar",
      "max_percent": 21,
      "min_percent": 0,
      "name": "Brown Sugar, Light",
      "slug": "generic-brown-sugar-light"
    },
    {
      "category": "munich",
      "max_percent": 38,
      "min_percent": 0,
      "name": "Munich Malt 10L",
      "slug": "briess-munich-malt-10l"
    },
    {
      "category": "base",
      "max_percent": 100,
      "min_percent": 27,
      "name": "Golden Promise",
      "slug": "generic-golden-promise"
    },
    {
      "category": "base",
      "max_percent": 60,
      "min_percent": 0,
      "name": "Vienna Malt",
      "slug": "weyermann-vienna-malt"
    },
    {
      "category": "rye",
      "max_percent": 17,
      "min_percent": 1,
      "name": "Brewers Rye Flakes",
      "slug": "briess-brewers-rye-flakes"
    },
    {
      "category": "specialty",
      "max_percent": 2,
      "min_percent": 2,
      "name": "Brown Malt",
      "slug": "generic-brown-malt"
    },
    {
      "category": "roasted",
      "max_percent": 3,
      "min_percent": 0,
      "name": "Roasted Barley",
      "slug": "briess-roasted-barley"
    },
    {
      "category": "crystal",
      "max_percent": 13,
      "min_percent": 0,
      "name": "Caramel Malt 90L",
      "slug": "briess-caramel-malt-90l"
    },
    {
      "category": "base",
      "max_percent": 100,
      "min_percent": 12,
      "name": "Pilsner Malt",
      "slug": "weyermann-pilsner-malt"
    },
    {
      "category": "specialty",
      "max_percent": 6,
      "min_percent": 6,
      "name": "Amber Malt",
      "slug": "generic-amber-malt"
    },
    {
      "category": "roasted",
      "max_percent": 2,
      "min_percent": 1,
      "name": "Chocolate Malt",
      "slug": "briess-chocolate-malt"
    },
    {
      "category": "specialty",
      "max_percent": 32,
      "min_percent": 0,
      "name": "Victory Malt",
      "slug": "briess-victory-malt"
    },
    {
      "category": "crystal",
      "max_percent": 14,
      "min_percent": 1,
      "name": "Caramel Malt 30L",
      "slug": "briess-caramel-malt-30l"
    },
    {
      "category": "base",
      "max_percent": 100,
      "min_percent": 29,
      "name": "Pale Ale Malt",
      "slug": "briess-pale-ale-malt"
    },
    {
      "category": "roasted",
      "max_percent": 2,
      "min_percent": 0,
      "name": "Black Malt",
      "slug": "briess-black-malt"
    },
    {
      "category": "base",
      "max_percent": 100,
      "min_percent": 24,
      "name": "Pilsen Malt",
      "slug": "briess-pilsen-malt"
    },
    {
      "category": "sugar",
      "max_percent": 12,
      "min_percent": 1,
      "name": "Honey",
      "slug": "generic-honey"
    },
    {
      "category": "crystal",
      "max_percent": 16,
      "min_percent": 0,
      "name": "CaraHell",
      "slug": "weyermann-carahell"
    },
    {
      "category": "crystal",
      "max_percent": 12,
      "min_percent": 1,
      "name": "Caramel Malt 60L",
      "slug": "briess-caramel-malt-60l"
    },
    {
      "category": "crystal",
      "max_percent": 10,
      "min_percent": 1,
      "name": "Caramel Vienne Malt 20L",
      "slug": "briess-caramel-vienne-malt-20l"
    },
    {
      "category": "munich",
      "max_percent": 49,
      "min_percent": 0,
      "name": "Munich Malt I",
      "slug": "weyermann-munich-malt-i"
    },
    {
      "category": "wheat",
      "max_percent": 40,
      "min_percent": 0,
      "name": "Pale Wheat Malt",
      "slug": "weyermann-pale-wheat-malt"
    },
    {
      "category": "munich",
      "max_percent": 54,
      "min_percent": 0,
      "name": "Munich Malt II",
      "slug": "weyermann-munich-malt-ii"
    },
    {
      "category": "flakes and adjuncts",
      "max_percent": 6,
      "min_percent": 1,
      "name": "Brewers Barley Flakes",
      "slug": "briess-brewers-barley-flakes"
    },
    {
      "category": "flakes and adjuncts",
      "max_percent": 21,
      "min_percent": 0,
      "name": "Brewers Red Wheat Flakes",
      "slug": "briess-brewers-red-wheat-flakes"
    },
    {
      "category": "crystal",
      "max_percent": 8,
      "min_percent": 3,
      "name": "CaraAroma",
      "slug": "weyermann-caraaroma"
    },
    {
      "category": "sugar",
      "max_percent": 13,
      "min_percent": 0,
      "name": "Sucrose (Table Sugar)",
      "slug": "generic-sucrose-table-sugar"
    },
    {
      "category": "crystal",
      "max_percent": 13,
      "min_percent": 1,
      "name": "Caramel Malt 40L",
      "slug": "briess-caramel-malt-40l"
    },
    {
      "category": "specialty",
      "max_percent": 5,
      "min_percent": 1,
      "name": "Special B",
      "slug": "generic-special-b"
    },
    {
      "category": "crystal",
      "max_percent": 16,
      "min_percent": 1,
      "name": "Caramel Malt 10L",
      "slug": "briess-caramel-malt-10l"
    },
    {
      "category": "roasted",
      "max_percent": 0,
      "min_percent": 0,
      "name": "Dark Chocolate Malt",
      "slug": "briess-dark-chocolate-malt"
    },
    {
      "category": "flakes and adjuncts",
      "max_percent": 7,
      "min_percent": 7,
      "name": "Flaked Rice",
      "slug": "generic-flaked-rice"
    },
    {
      "category": "flakes and adjuncts",
      "max_percent": 23,
      "min_percent": 0,
      "name": "Brewers Oat Flakes",
      "slug": "briess-brewers-oat-flakes"
    },
    {
      "category": "wheat",
      "max_percent": 39,
      "min_percent": 0,
      "name": "Wheat Malt, Red",
      "slug": "briess-wheat-malt-red"
    },
    {
      "category": "sugar",
      "max_percent": 1,
      "min_percent": 1,
      "name": "Candi Sugar, Clear",
      "slug": "generic-candi-sugar-clear"
    },
    {
      "category": "roasted",
      "max_percent": 3,
      "min_percent": 1,
      "name": "Pale Chocolate Malt",
      "slug": "generic-pale-chocolate-malt"
    },
    {
      "category": "sugar",
      "max_percent": 7,
      "min_percent": 7,
      "name": "Brown Sugar, Dark",
      "slug": "generic-brown-sugar-dark"
    },
    {
      "category": "specialty",
      "max_percent": 11,
      "min_percent": 0,
      "name": "Carapils",
      "slug": "weyermann-carapils"
    },
    {
      "category": "base",
      "max_percent": 36,
      "min_percent": 0,
      "name": "Goldpils Vienna Malt",
      "slug": "briess-goldpils-vienna-malt"
    },
    {
      "category": "rye",
      "max_percent": 32,
      "min_percent": 0,
      "name": "Rye Malt",
      "slug": "briess-rye-malt"
    },
    {
      "category": "base",
      "max_percent": 89,
      "min_percent": 0,
      "name": "6-Row Brewers Malt",
      "slug": "generic-6-row-brewers-malt"
    },
    {
      "category": "crystal",
      "max_percent": 12,
      "min_percent": 2,
      "name": "CaraMunich I",
      "slug": "weyermann-caramunich-i"
    },
    {
      "category": "crystal",
      "max_percent": 12,
      "min_percent": 0,
      "name": "Caramel Malt 80L",
      "slug": "briess-caramel-malt-80l"
    },
    {
      "category": "crystal",
      "max_percent": 14,
      "min_percent": 0,
      "name": "Caramel Malt 20L",
      "slug": "briess-caramel-malt-20l"
    },
    {
      "category": "crystal",
      "max_percent": 10,
      "min_percent": 3,
      "name": "CaraMunich III",
      "slug": "weyermann-caramunich-iii"
    },
    {
      "category": "munich",
      "max_percent": 20,
      "min_percent": 0,
      "name": "Munich Malt 20L",
      "slug": "briess-munich-malt-20l"
    },
    {
      "category": "wheat",
      "max_percent": 39,
      "min_percent": 0,
      "name": "Wheat Malt, White",
      "slug": "briess-wheat-malt-white"
    },
    {
      "category": "specialty",
      "max_percent": 16,
      "min_percent": 0,
      "name": "Honey Malt",
      "slug": "gambrinus-honey-malt"
    },
    {
      "category": "sugar",
      "max_percent": 8,
      "min_percent": 8,
      "name": "Turbinado",
      "slug": "generic-turbinado"
    },
    {
      "category": "specialty",
      "max_percent": 26,
      "min_percent": 0,
      "name": "Carapils Malt",
      "slug": "briess-carapils-malt"
    },
    {
      "category": "base",
      "max_percent": 100,
      "min_percent": 39,
      "name": "Brewer's Malt",
      "slug": "briess-brewers-malt"
    },
    {
      "category": "crystal",
      "max_percent": 14,
      "min_percent": 1,
      "name": "CaraRed",
      "slug": "weyermann-carared"
    },
    {
      "category": "sugar",
      "max_percent": 13,
      "min_percent": 0,
      "name": "Dextrose (Corn Sugar)",
      "slug": "generic-dextrose-corn-sugar"
    },
    {
      "category": "crystal",
      "max_percent": 11,
      "min_percent": 1,
      "name": "CaraMunich II",
      "slug": "weyermann-caramunich-ii"
    }
  ],
  "hops": {
    "unique_hop_count": 2
  },
  "name": "American Pale Ale",
  "sensory_data": [
    {
      "max": 3.365,
      "mean": 2.916146712398855,
      "min": 2.467,
      "name": "sweet"
    },
    {
      "max": 3.343,
      "mean": 2.272497928450988,
      "min": 1.202,
      "name": "malty"
    },
    {
      "max": 2.194,
      "mean": 0.8105195038858988,
      "min": 0,
      "name": "bready"
    },
    {
      "max": 2.484,
      "mean": 0.878084873230749,
      "min": 0,
      "name": "honey"
    },
    {
      "max": 1.237,
      "mean": 0.9792710868892691,
      "min": 0.721,
      "name": "biscuit"
    },
    {
      "max": 1.426,
      "mean": 0.7981138662334352,
      "min": 0.171,
      "name": "nutty"
    },
    {
      "max": 1.503,
      "mean": 0.8658730742853765,
      "min": 0.229,
      "name": "toast"
    },
    {
      "max": 2.447,
      "mean": 1.3050411498583776,
      "min": 0.163,
      "name": "grainy"
    },
    {
      "max": 0.155,
      "mean": 0.029772423490681522,
      "min": 0,
      "name": "bitter"
    },
    {
      "max": 0.125,
      "mean": 0.023547450826199096,
      "min": 0,
      "name": "coffee"
    },
    {
      "max": 0.184,
      "mean": 0.03665317385854709,
      "min": 0,
      "name": "cocoa"
    },
    {
      "max": 0.121,
      "mean": 0.02282087805360272,
      "min": 0,
      "name": "dark_chocolate"
    },
    {
      "max": 0.271,
      "mean": 0.053585272140014,
      "min": 0,
      "name": "roasted_almond"
    },
    {
      "max": 0.237,
      "mean": 0.049314324580260985,
      "min": 0,
      "name": "dried_fruit"
    },
    {
      "max": 0.073,
      "mean": 0.015187607143741448,
      "min": 0,
      "name": "wood_smoke"
    },
    {
      "max": 0.29,
      "mean": 0.051926418897381456,
      "min": 0,
      "name": "clove"
    },
    {
      "max": 0.596,
      "mean": 0.16277682305134986,
      "min": 0,
      "name": "almond"
    },
    {
      "max": 0.673,
      "mean": 0.14492434825550934,
      "min": 0,
      "name": "hazelnut"
    },
    {
      "max": 0.442,
      "mean": 0.1369967561774701,
      "min": 0,
      "name": "raisin"
    },
    {
      "max": 0.429,
      "mean": 0.09917627404252223,
      "min": 0,
      "name": "vanilla"
    },
    {
      "max": 0.298,
      "mean": 0.06767928608836735,
      "min": 0,
      "name": "marmalade"
    },
    {
      "max": 0.638,
      "mean": 0.20076257504222464,
      "min": 0,
      "name": "toffee"
    },
    {
      "max": 0.81,
      "mean": 0.27042595516571905,
      "min": 0,
      "name": "caramel"
    },
    {
      "max": 0.25,
      "mean": 0.05257874075549529,
      "min": 0,
      "name": "dark_caramel"
    },
    {
      "max": 0.416,
      "mean": 0.08784951939776167,
      "min": 0,
      "name": "sour"
    },
    {
      "max": 2.0,
      "mean": 1.0313820831342422,
      "min": 0,
      "name": "graham_cracker"
    },
    {
      "max": 0.324,
      "mean": 0.04248405996864342,
      "min": 0,
      "name": "wheat_flour"
    },
    {
      "max": 0.431,
      "mean": 0.05543663900772446,
      "min": 0,
      "name": "bread_dough"
    },
    {
      "max": 0.12,
      "mean": 0.03608096530126564,
      "min": 0,
      "name": "sourdough"
    },
    {
      "max": 0.157,
      "mean": 0.039378042270742215,
      "min": 0,
      "name": "roasted_marshmallow"
    },
    {
      "max": 0.161,
      "mean": 0.04064358413934273,
      "min": 0,
      "name": "burnt_sugar"
    },
    {
      "max": 0.097,
      "mean": 0.02378339065891801,
      "min": 0,
      "name": "prune"
    },
    {
      "max": 0,
      "mean": 0,
      "min": 0,
      "name": "raisin_bread"
    },
    {
      "max": 0,
      "mean": 0,
      "min": 0,
      "name": "woody"
    },
    {
      "max": 0,
      "mean": 0,
      "min": 0,
      "name": "dark_toast"
    },
    {
      "max": 0.245,
      "mean": 0.028822101631262535,
      "min": 0,
      "name": "bread_crust"
    },
    {
      "max": 0.16,
      "mean": 0.01605640372339671,
      "min": 0,
      "name": "earthy"
    },
    {
      "max": 0.16,
      "mean": 0.01605640372339671,
      "min": 0,
      "name": "rye_bready"
    },
    {
      "max": 0.014,
      "mean": 0.0009954108725997162,
      "min": 0,
      "name": "roasted"
    },
    {
      "max": 0.009,
      "mean": 0.0005985895987572114,
      "min": 0,
      "name": "burnt"
    },
    {
      "max": 0.009,
      "mean": 0.00046239743066968917,
      "min": 0,
      "name": "milk_chocolate"
    },
    {
      "max": 0,
      "mean": 0,
      "min": 0,
      "name": "tobacco"
    },
    {
      "max": 0.031,
      "mean": 0.0015157501195152308,
      "min": 0,
      "name": "molasses"
    },
    {
      "max": 0,
      "mean": 0,
      "min": 0,
      "name": "creamy"
    },
    {
      "max": 0.153,
      "mean": 0.014451907766411812,
      "min": 0,
      "name": "pretzel"
    },
    {
      "max": 0.088,
      "mean": 0.008258233009378177,
      "min": 0,
      "name": "tart"
    },
    {
      "max": 0,
      "mean": 0,
      "min": 0,
      "name": "ash"
    },
    {
      "max": 0,
      "mean": 0,
      "min": 0,
      "name": "barbeque"
    }
  ],
  "slug": "american-pale-ale",
  "stats": {
    "abv": {
      "high": 6.2,
      "low": 4.5
    },
    "fg": {
      "high": 1.015,
      "low": 1.01
    },
    "ibu": {
      "high": 50.0,
      "low": 30.0
    },
    "og": {
      "high": 1.06,
      "low": 1.045
    },
    "srm": {
      "high": 10.0,
      "low": 5.0
    }
  },
  "unique_fermentable_count": 3
}
