#!/usr/bin/env python3
"""Freeze a generation-proved default brief for every shipped style.

Run from the repo root::

    python3 scripts/build_style_defaults.py

It rewrites ``brewgen/backend/data/style_defaults.json``, the table the style
payload carries and the brief editor opens on, plus the two American Pale Ale
fixtures the browser tests read: the real style payload the editor loads, and
the exact brief an untouched default sends. Run it whenever a style is added or
its grain, category or sensory model changes; ``tests/test_style_defaults.py``
fails if the committed table or either fixture has gone stale.

The typical brief for a style is its midpoint strength, its midpoint colour, and
its five strongest style-mentioned flavours each at the word step its corpus
mean earns. That brief is often impossible, so when generation cannot answer it
the search repairs it in a fixed order, always taking the first brief that
generates:

1. turn the levels down, boldest first, never below ``hint``;
2. nudge the target colour inside the style's own slider range, nearest first;
3. drop flavour rows, weakest first -- last resort only.

Every candidate is proved by the same generation the visitor's Generate reaches,
through the same strict ``version: 1`` contract, so what the editor displays is
what was proved.
"""

import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from brewgen.backend import style_defaults                      # noqa: E402
from brewgen.backend import views                               # noqa: E402
from brewgen.backend.solver.fermentables import (               # noqa: E402
    FermentableSolver, GenerationStatus)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(
    REPO, "brewgen", "backend", "data", "style_defaults.json")

# The browser tests must exercise a real style payload, not a reduced stand-in:
# the reduced fixture is what hid an impossible opening brief in the first place.
FIXTURES = os.path.join(REPO, "brewgen", "frontend", "tests", "fixtures")
FIXTURE_STYLE = "american-pale-ale"
GENERATED_NOTE = (
    "Generated by scripts/build_style_defaults.py -- do not edit by hand.")


def style_payload(slug):
    """The per-style payload the editor loads, straight from the route."""
    with views.app.test_client() as client:
        return client.get("/api/v1/styles/%s" % slug).get_json()


def candidate_rows(style):
    """The style's strongest mentioned flavours, boldest corpus mean first.

    BJCP names the descriptors a style is known for; the corpus says how loud
    each one actually runs. Ranking by mean (ties by name) keeps a style opening
    on what it tastes of, where taking the first five names alphabetically once
    seeded rows whose corpus range was flat zero.
    """
    by_name = {item["name"]: item for item in style.get("sensory_data") or []}
    mentioned = sorted(style.get("bjcp_sensory") or {})
    rows = [by_name[name] for name in mentioned if name in by_name]
    rows.sort(key=lambda item: (-item["mean"], item["name"]))
    return rows[:style_defaults.MAX_ROWS]


def slider_bounds(style):
    """The strength and colour sliders the editor draws for this style."""
    stats = style.get("stats") or {}
    abv = stats.get("abv") or style_defaults.FALLBACK_ABV
    srm = stats.get("srm") or style_defaults.FALLBACK_SRM
    return (
        style_defaults.round1((abv["low"] + abv["high"]) / 2),
        style_defaults.js_round(srm["low"]),
        style_defaults.js_round(srm["high"]),
        style_defaults.js_round((srm["low"] + srm["high"]) / 2),
    )


def colour_candidates(low, high, middle):
    """Every colour the slider offers, nearest the midpoint first."""
    return sorted(range(low, high + 1), key=lambda srm: (abs(srm - middle), srm))


def level_ladder(rows):
    """Seeded word steps, then one step down at a time until all read ``hint``.

    The boldest row eases first; ties go to the least characteristic descriptor,
    so a style gives up its weakest claim before its defining one. ``none`` is
    the avoid state and is never a seeded step, so the ladder stops at ``hint``.
    """
    levels = [style_defaults.seed_level(row["mean"]) for row in rows]
    yield list(levels)
    while any(level > 1 for level in levels):
        index = min(
            (i for i, level in enumerate(levels) if level > 1),
            key=lambda i: (-levels[i], rows[i]["mean"], rows[i]["name"]))
        levels[index] -= 1
        yield list(levels)


def generates(style, default):
    """True when generation returns at least one bill for this default brief."""
    payload = style_defaults.build_brief(style, default)
    brief = views.CONTRACT.parse(payload)
    solver = FermentableSolver(
        brief.grains, brief.categories,
        max_unique_grains=brief.max_unique,
        sensory_keywords=brief.sensory_keywords,
        sensory_bounds=brief.sensory_bounds,
        config=views.SOLVER_CONFIG)
    result = solver.generate(
        original_sg=brief.original_sg,
        target_volume_gallons=brief.target_volume_gallons,
        mash_efficiency=brief.mash_efficiency,
        min_srm=brief.min_srm,
        max_srm=brief.max_srm)
    return (result.status in (GenerationStatus.COMPLETE, GenerationStatus.PARTIAL)
            and bool(result.alternatives))


def proved_default(style):
    """The first brief in repair order that generation proves, or None."""
    rows = candidate_rows(style)
    abv, srm_low, srm_high, srm_middle = slider_bounds(style)
    colours = colour_candidates(srm_low, srm_high, srm_middle)

    for count in range(len(rows), -1, -1):
        kept = rows[:count]
        for srm in colours:
            for levels in level_ladder(kept):
                default = {
                    "abv": abv,
                    "srm": srm,
                    "flavors": [{"name": row["name"], "level": level}
                                for row, level in zip(kept, levels)],
                }
                if generates(style, default):
                    return default
    return None


def write_fixtures(style, default):
    """Refresh the browser fixtures anchored on one real style.

    ``apa-style.js`` is the payload the editor actually loads. ``apa-proved-
    brief.json`` is what this build step proved: both the browser's brief maths
    and this script's mirror of it must reproduce it byte for byte, which is how
    the two stay honest about sending the same request.
    """
    payload = json.dumps(style, indent=2, sort_keys=True)
    with open(os.path.join(FIXTURES, "apa-style.js"), "w",
              encoding="utf-8") as handle:
        handle.write("/* %s */\n\nexport const style = %s\n"
                     % (GENERATED_NOTE, payload))
    with open(os.path.join(FIXTURES, "apa-proved-brief.json"), "w",
              encoding="utf-8") as handle:
        json.dump(style_defaults.build_brief(style, default), handle, indent=2)
        handle.write("\n")


def main():
    slugs = views.all_styles.get_style_slugs()
    table = {}
    unproved = []
    fixture_payload = None
    started = time.monotonic()

    for slug in slugs:
        style = style_payload(slug)
        default = proved_default(style)
        if default is None:
            unproved.append(slug)
            print("  !! %s: no brief generates" % slug)
            continue
        table[slug] = default
        if slug == FIXTURE_STYLE:
            # The payload was served against the table being replaced; the
            # fixture must carry the default this run just proved.
            style["default"] = default
            fixture_payload = style
        rows = " ".join("%s=%s" % (row["name"], style_defaults.LEVELS[row["level"]])
                        for row in default["flavors"])
        print("  %-32s %.1f%% %2d SRM  %s" % (slug, default["abv"], default["srm"], rows))

    if fixture_payload is not None:
        write_fixtures(fixture_payload, table[FIXTURE_STYLE])

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        json.dump({
            "brief_version": 1,
            "styles": {slug: table[slug] for slug in sorted(table)},
        }, handle, indent=2, sort_keys=False)
        handle.write("\n")

    print("\n%d/%d styles proved in %.1fs -> %s"
          % (len(table), len(slugs), time.monotonic() - started, OUTPUT))
    if unproved:
        print("unproved: %s" % ", ".join(unproved))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
